[Cr, Ci] = meshgrid(cr1:dc:cr2, ci1:dc:ci2);
contour(Cr, Ci, p1_in_mats{1,1}, [0, 0], '-', 'LineWidth', 1.4, 'LineColor', 'r');
hold on;
contour(Cr, Ci, p1_in_mats{1,2}, [0, 0], '-', 'LineWidth', 1.4, 'LineColor', 'b');
xlabel('$\mathrm{Re}(c)$', 'Interpreter', 'latex', 'FontSize', 16);
ylabel('$\mathrm{Im}(c)$', 'Interpreter', 'latex', 'FontSize', 16);
set(gca, 'TickLabelInterpreter','latex', ...
		 'FontSize', 16, ...
		 'LineWidth', 1.4, ...
		 'XColor', 'k', ...
		 'YColor', 'k', ...
		 'TickDir', 'in', ...
		 'TickLength', [0.015,0.025]);
axis equal;
set(gcf, 'Position', [500, 200, 500, 500]);
legend('$\mathrm{Re}\left[p_1(0)\right]$', '$\mathrm{Im}\left[p_1(0)\right]$', ...
	   'Interpreter', 'latex', ...
	   'Location', 'southwest', ...
	   'FontSize', 16, ...
	   'EdgeColor', 'k');